# Generated by Django 6.0 on 2026-01-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_phone_user_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
