# Generated by Django 6.0 on 2026-05-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_phone_number_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
