[tool.poetry]
name = "drf"  # можно оставить или поменять на "lms"
version = "0.1.0"
description = "Django LMS project"
authors = ["mike"]
readme = "readme.md"
packages = [
    {include = "config"},  # твоя папка с настройками Django
    {include = "courses"},
    {include = "users"},
    {include = "manage.py"}  # если хочешь включить manage.py
]

[tool.poetry.dependencies]
python = "^3.13"
djangorestframework = "^3.16.1"
black = "^25.12.0"
isort = "^7.0.0"
django = "^6.0"
psycopg2-binary = "^2.9.11"
pillow = "^12.1.0"
python-dotenv = "^1.2.1"
dotenv = "^0.9.9"
django-filter = "^25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"