# Generated by Django 6.0 on 2026-01-04 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название курса", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Превью-изображение курса",
                        null=True,
                        upload_to="courses/previews/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Подробное описание курса", verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название урока", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Подробное описание урока", verbose_name="description"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Превью-изображение урока",
                        null=True,
                        upload_to="lessons/previews/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на видео урока",
                        null=True,
                        verbose_name="video URL",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Курс, к которому принадлежит урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
            },
        ),
    ]
